# This file allows for easy starting of a Jena Fuseki server using Docker
# Compose for validating query results.

version: '3'

services:
  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=pw123
